FROM oven/bun:1

ARG DATABASE_URL

WORKDIR /app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json
COPY ./apps/web ./apps/web

RUN bun install
RUN bun run db:generate

EXPOSE 3000

CMD [ "bun", "run", "start:frontend" ]